### ISSUE TITLE
Issue faced while creating the project

### ISSUE THREAD

**Issue by vedangdate** [lucavenir/riverpod_core_brick#1]
## Setup
Because I learned about Mason today, I basically did whatever they asked me to do
[Brickhub Riverpod Core Usage](https://brickhub.dev/bricks/riverpod_core/0.0.2#usage)

except I also had to do "mason init" in between.

After that I waited for the "make" command to complete. And here's what I got

![Terminal Screenshot](https://github.com/lucavenir/riverpod_core_brick/assets/7449085/ccdb1366-d2ac-49fa-ab65-dfaeab510e46)

I upgraded to newest version of flutter today so maybe that might be the issue. Here's my flutter doctor command.

```sh
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.8, on Microsoft Windows [Version 10.0.22621.2428], locale en-GB)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.22)
[√] Android Studio (version 2022.2)
[√] VS Code, 64-bit edition (version 1.83.1)
[√] Connected device (3 available)
[√] Network resources
```

**Comment by lucavenir** [comment]
>  I basically did whatever they asked me to do

Unluckily that page is auto generated by `brickhub.dev`, there's little I can do about it.

About your issue, for me to be able to reproduce the issue, I need you to give me the command you're running, or the configuration you're using with this brick.

**Comment by ghost** [comment]
Oh, okay. Well, I can copy the commands over here.

```sh
mason add -g riverpod_core
```

```sh
mason make riverpod_core
```

I then gave it name, org, desc and publish inputs. Rest all were defaults.

**Comment by ghost** [comment]
Any update on this?

**Comment by lucavenir** [comment]
Hi there, I'm sorry I didn't reply, but I am unalbe to reproduce this currently, I am using this brick without any problem. I'm currently not sure how to pinpoint this issue

**Comment by vedangdate** [comment]
Hey, sorry about the multiple accounts....I'll stick to this one from now on

I see. Okay, I'll try this again after I am relieved from some of my current tasks. Thanks for letting me know!
Will reopen this issue if the same error comes up
